eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3909/eureka
  instance:
    prefer-ip-address: true

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: conversation-service
        uri: lb://conversation-service
        predicates:
        - Path=/conversation/**
      - id: message-service
        uri: lb://message-service
        predicates:
        - Path=/message
      - id: subscribe-service
        uri: lb://subscribe-service
        predicates:
        - Path=/subscriptions
      - id: discovery-server
        uri: http://127.0.0.1:3909
        predicates:
        - Path=/eureka/web
        filters:
        - SetPath=/
      - id: discovery-server-static
        uri: http://127.0.0.1:3909
        predicates:
        - Path=/eureka/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO

server:
  port: 3900
